name: CI/CD Pipeline

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  test:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # ativa o cache do npm para reduzir o tempo de download de pacotes em builds futuros
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
    
    # a chave da API não é necessária nesse job pois o teste usa dados estáticos